### ISSUE TITLE
Support Mermaid diagrams

### ISSUE THREAD

**Issue by sentientwaffle** [tigerbeetledb/docs#3]
https://docs.tigerbeetle.com/usage/integration#api-layer-architecture
https://docusaurus.io/docs/next/markdown-features/diagrams

I think it requires updating docusaurus (in addition to the plugin).

**Comment by eatonphil** [comment]
I'll do it right now.

**Comment by eatonphil** [comment]
Closed in [9304bbf9b1b000801429389490cc0ac6d029b1a4](https://github.com/tigerbeetledb/docs/commit/9304bbf9b1b000801429389490cc0ac6d029b1a4).

<img width="1512" alt="Screen Shot 2022-12-16 at 1 00 58 PM" src="https://user-images.githubusercontent.com/3925912/208160476-3e19aff7-a0eb-428e-afba-b00a356a2557.png">
